server:
  port: 8080
  tomcat:
    max-threads: 200

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: PT@2586151267o
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: false

  security:
    user:
      name: admin
      password: admin

management:
  app:
    jwtSecret: "bWFuYWdlbWVudFNlY3JldEtleQ=="
    jwtExpirationMs: 86400000

logging:
  level:
    org.springframework: INFO
